[google]
type = "service_account"
project_id = "radar-de-problemas-sgs"
private_key_id = "67f053132a49ff61fbf9cb5a042d34c9f9f4f7bd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCdUhQRRxdwLjOw
k1M2RZ5wrqGQYbZlYYMGr7126gqxDaaHedvYBQL1ShNZpmoSBKu67yUFbZ5+rHo1
85P5yUPagkWa5o2ZGQaCJMiuWYbbTiX3ZwReNl7gZyMlCl9NiPzbK8nIITAVqKOv
Ed8IMFXRHvmE2oUce3TS1LCKsxqXy8Hl+eJIEUi5icg/5kKBQTC7rBq9gxdHhgIl
voi6mcHCH/Bf34izHjhdgqWRq4OJocQyo6ZU+OPE6/QGIt3k0+Cw2iiZhoWEk0yb
BFlPBUChgh7ViuV4ubDgVRHw1XdoYDIElKSvoh6jmpWoYBpq8bwt7Swx0gSFuUtr
zWaflRKvAgMBAAECggEAScXeJDYGvzPjSGflyxr9kBDMMcUof8Uo6N9LhTJ+PgXN
NFWIKvY6q2UHyvAXaIipMVmIrlF31CY0jw1AtI9VkuepFVkNSKBsJWZzdxMDgt7U
Pf6glT+A4VFsMSf6hgT5shuIHaG2h0mULHpAcPodnBme39aLOk6Ie3+CpCAWFd0Z
iNOMtfrf8FBkaYanSvhJV9LQPVki8eumJUduqeW94zuj3d0aM5IxdJAMXLrLfLtW
N5gglmu+iOYxQVB8FYHdiRJLM3+vj0AXPL/CJPnl43hJEB+1XhbekRS2OpwkQ96u
Wy4LIKlOHX+rHCc7plnoXPntJiYSvnmSRBCSDzrZQQKBgQDbD7O0XwDyf2JAJFoD
q13X1V6vjLYiUXHyTVmBKwRIcqXtjO4UmODeJH/bqg1Zyy780NCqUFCddCbM0Y8D
RKHaC+7u/dL+XEGBD/EZbkZF3NLNWGHmxMbdRwAhAxPvcy1ziodrWp8Le9QjWQkz
kfudlmieDtXJ5H6eMXgVxuBOwQKBgQC32TFt2/B0Y2jtnOHVPWyo3Kv0aI/yKGHS
RVy2aoh37HmZDfPn+YhzaQqT65ThtvYRSCPbvUASVM/7FOSCcN121AjQnGoYSEWc
1q6VQgTBp7dMUiig5I1CHNv6vAxRgC37Smnd9Y9LbP+yg7LZbFA/aa4LrkfpX/2Z
efeR0DstbwKBgQCPcinH7AovwVByFhvHmVi7M+Jr7CV8NX77HsGEfsmwMzsKYiWo
4S8m6Bm9mw5hBVcAgDCTxkHzyRJ7PqJ6jl+56+SLJTUcEQdn3yuO7pIfv2lexAhf
1+0tCwg/lcdhHjfeGBFzMAVDvNN+ThhjZ62vVMWu8qH2MaTkLBqpj/BkQQKBgQCN
xEWBWWAJ375Bu//I1xy6+a7/QMH/EXSdGC9t2qhxEUCS7VdvQdQeapllhvu/Mb59
hQthnoWRnSTjkDDFBRNBVi+V7YdCQjirwD/PiKDyU8ncaF478wGaQXa/2dIF5rmO
VMteBMUCfIKPvU5kqkkXHP7Asxtwsjxz5MErB08asQKBgDfBSC09LNREGAqElUT5
XY4T6iyoKX6aMR2IJx02v5OmH7C+ZwKqf4sFFxfolbxfq3XT/2hbxkhdMCjEOEaY
ARBlraMbNtTX+hopJpJa4D9Ln3xX673WpxM1x3XoE9SQwPGV4q/PbmznUOrEINt1
JxdGj3oX8E5Nhihyhz7Q+gNP
-----END PRIVATE KEY-----"""
client_email = "radar-de-problemas-sgs@radar-de-problemas-sgs.iam.gserviceaccount.com"
client_id = "109192772731518776154"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/radar-de-problemas-sgs%40radar-de-problemas-sgs.iam.gserviceaccount.com"
universe_domain = "googleapis.com"